import { useState, useEffect, useRef } from "react";
import html2canvas from "html2canvas";
import { ExternalLink, Copy, Check, Eye, Sparkles, Download } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { queryKeys } from "@/lib/query-keys";
import type { AppointmentWithRelations } from "./types";

interface ViewCardDialogProps {
  apt: AppointmentWithRelations | null;
  onClose: () => void;
}

export function ViewCardDialog({ apt, onClose }: ViewCardDialogProps) {
  const { toast } = useToast();
  const [linkCopied, setLinkCopied] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [localToken, setLocalToken] = useState<string | null>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const autoGeneratedRef = useRef(false);

  if (!apt) return null;

  const token = localToken || apt.rescheduleToken;
  const cardUrl = token ? `${window.location.origin}/card/${token}` : null;
  const isViewed = !!apt.cardViewedAt;

  const handleGenerateToken = async () => {
    if (generating) return;
    setGenerating(true);
    try {
      const res = await apiRequest("POST", `/api/appointments/${apt.id}/generate-card-token`, {});
      const data = await res.json() as { token: string };
      setLocalToken(data.token);
      queryClient.invalidateQueries({ queryKey: queryKeys.appointments });
      toast({ title: "Card link generated", description: "Appointment card link is now ready." });
    } catch {
      toast({ title: "Failed to generate link", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (!apt || token || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    handleGenerateToken();
  }, [apt?.id]);

  const handleCopyLink = async () => {
    if (!cardUrl) return;
    await navigator.clipboard.writeText(cardUrl);
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
    toast({ title: "Link copied", description: "Appointment card link copied to clipboard." });
  };

  const handleDownload = async () => {
    const iframeDoc = iframeRef.current?.contentDocument;
    if (!iframeDoc?.body) return;
    try {
      const canvas = await html2canvas(iframeDoc.body, {
        useCORS: true,
        allowTaint: false,
        backgroundColor: "#ffffff",
        scale: 2,
      });
      const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/jpeg", 0.95));
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `appointment-card-${apt.id}.jpg`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast({ title: "Download failed", description: "Could not generate card image.", variant: "destructive" });
    }
  };

  return (
    <Dialog open={!!apt} onOpenChange={(open) => { if (!open) { setLocalToken(null); autoGeneratedRef.current = false; onClose(); } }}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-hidden p-0">
        <DialogHeader className="px-6 py-4 border-b flex-row items-center justify-between">
          <DialogTitle className="flex items-center gap-2">
            <Eye className="h-5 w-5" />
            Appointment Card
            {isViewed && (
              <Badge variant="secondary" className="ml-2 text-xs bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400" data-testid="badge-card-viewed">
                <Check className="h-3 w-3 mr-1" />
                Viewed
              </Badge>
            )}
          </DialogTitle>
          <div className="flex items-center gap-2">
            {cardUrl ? (
              <>
                <Button size="sm" variant="outline" onClick={handleCopyLink} className="gap-1.5 text-xs" data-testid="button-card-copy-link">
                  {linkCopied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                  {linkCopied ? "Copied!" : "Copy Link"}
                </Button>
                <Button size="sm" variant="outline" onClick={handleDownload} className="gap-1.5 text-xs" data-testid="button-card-download">
                  <Download className="h-3.5 w-3.5" />
                  Download
                </Button>
                <a href={cardUrl} target="_blank" rel="noopener noreferrer">
                  <Button size="sm" variant="ghost" className="gap-1.5 text-xs" data-testid="button-card-open-tab">
                    <ExternalLink className="h-3.5 w-3.5" />
                    Open
                  </Button>
                </a>
              </>
            ) : (
              <Button
                size="sm"
                variant="outline"
                onClick={handleGenerateToken}
                disabled={generating}
                className="gap-1.5 text-xs"
                data-testid="button-card-generate-link"
              >
                <Sparkles className="h-3.5 w-3.5" />
                {generating ? "Generating…" : "Generate Card Link"}
              </Button>
            )}
          </div>
        </DialogHeader>
        <div className="flex-1 overflow-hidden" style={{ height: "calc(90vh - 100px)" }}>
          {token ? (
            <iframe
              ref={iframeRef}
              src={`/card/${token}`}
              className="w-full h-full border-none"
              title="Appointment Card Preview"
              data-testid="iframe-card-preview"
            />
          ) : (
            <div className="flex items-center justify-center h-full text-muted-foreground text-sm p-8 text-center">
              <div>
                <Eye className="h-8 w-8 mx-auto mb-3 opacity-30" />
                <p className="font-medium mb-1">Generating card link…</p>
                <p className="text-xs text-muted-foreground">Please wait while we create a shareable appointment card.</p>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
